name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOURCE_FOLDER: './catalog/*'
  DESTINATION_REPO: 'grokspawn/cool-catalog'
  DESTINATION_FOLDER: './catalog/'
  DESTINATION_HEAD_BRANCH: cool-catalog-contributor

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fix git safe.directory in container
      run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig

    - name: Build Catalog
      run: make catalog

    - name: Generate Devfiles
      uses: release-engineering/tap-fitter@main
      with:
        catalog-path:
        composite-path:
        provider:

    - name: Validate
      uses: joelanford/opm-validate@main
      with:
        catalog: catalog

    - name: Release
      if: github.event_name == 'push'
      uses: grokspawn/action-pull-request-another-repo@v1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: ${{ SOURCE_FOLDER }}
        destination_repo: ${{ DESTINATION_REPO }}
        destination_folder: ${{ DESTINATION_FOLDER }}
        destination_head_branch: ${{ DESTINATION_HEAD_BRANCH}}-${{ github.actor }}
        user_email: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        user_name: ${{ github.actor }}
